sonar.projectKey=cgaell_mgc-autos
sonar.organization=cgaell

# Rutas de código fuente a auditar
sonar.sources=src
sonar.tests=src/tests

# Exclusiones críticas (evita analizar coverage, node_modules y librerías públicas)
sonar.exclusions=**/coverage/**,**/node_modules/**,**/public/docs/**

# Integración del reporte de cobertura de Jest (LCOV)
sonar.javascript.lcov.reportPaths=coverage/lcov.info