version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: mgc-database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: milleniumglobal
      MYSQL_DATABASE: mgc_seguros
      MYSQL_USER: mgc_admin
      MYSQL_PASSWORD: milleniumglobal
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: